    $(".sunmit_xx").click(function(){
        $.ajax({
            method:'post',
            url:'../php/login.php',
            data:{
                username:$(".username").val(),
                password:$(".password").val()
            },
            success:function(data){
                if(data.code==1){
                    sessionStorage.setItem('un',data.data.username);
                    location.href="../pages/index.html";
                }else(
                    $(".login_ts").html("用户名或密码错误").css({
                        color:"red"
                    })
                )
            },
            dataType:"json"
        })
    })
